# Site settings
title: Tony Wolf - IT Systems Engineering & Consulting
email: info@tony-wolf.de
description: > # this means to ignore newlines until "baseurl:"
  Systems Engineer, Programer and life discoverer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  twolfy

# Author settings
author_email: info@tony-wolf.de
author:
  display_name: Tony Wolf

# default settings for posts
status: publish
published: true

# Build settings
markdown: kramdown
destination: "../htdocs/"
